### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by ukrolelo** [max13fr/Airzonecloud-HomeAssistant#11]
Hello !
Thank you for this integration!
Please if you have time can you help me to figure it out,why its not working?

Conf check
Platform error climate.airzonecloud - Integration 'airzonecloud' not found.

config/custom_components/airzonecloud/
__init__.py
climate.py
const.py
manifest.py

conf yaml
climate:
  - platform: airzonecloud
    username: xxx@xxx
    password: xxxxx

Log:
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:454
Integration: Hass.io (documentation, issues)
First occurred: 1:02:06 PM (2 occurrences)
Last logged: 1:05:17 PM

Platform error climate.airzonecloud - Integration 'airzonecloud' not found.

Thank you!

**Comment by gabrio79** [comment]
have you added files in config/custom_components/airzone/ ? 
below my config in configuration.yaml

```
# Integrazione Airzone
climate:
  - platform: airzonecloud
    username: !secret airzone_username
    password: !secret airzone_password
    scan_interval: 30
```
