### ISSUE TITLE
Humidity not being recorded in history

### ISSUE THREAD

**Issue by jd1900** [max13fr/Airzonecloud-HomeAssistant#16]
I can see target temperature and current temperature in the history tab:
![image](https://user-images.githubusercontent.com/63632981/123537835-e036f700-d731-11eb-8e7d-ebb336bf6e37.png)

However, I can't see the current_humidity, despite being a valid attribute that is retrieved and that I can use:
![image](https://user-images.githubusercontent.com/63632981/123537857-fba20200-d731-11eb-8d4e-102edf400ce7.png)

It would be great to be able to record it.

**Comment by bvis** [comment]
You can record it creating a new sensor from the obtained value, for example:

```
    - platform: template
      sensors:
        airzone_temperature_comedor:
          friendly_name: "Temperatura Comedor"
          value_template: "{{ state_attr('climate.airzone_comedor', 'current_temperature') }}"
          unit_of_measurement: "°C"
          device_class: "temperature"
        airzone_humidity_comedor:
          friendly_name: "Humedad Comedor"
          value_template: "{{ state_attr('climate.airzone_comedor', 'current_humidity') }}"
          unit_of_measurement: "%"
          device_class: "humidity"
```
