### ISSUE TITLE
Temperature in integer

### ISSUE THREAD

**Issue by landaisbenj** [max13fr/Airzonecloud-HomeAssistant#17]
Hello, i would do that :
```
binary_sensor:
  - platform: template
    sensors:
      temp_zone_vie:
            unique_id: 4cbf0f03-2f7e-4697-ad20-098a1288f4c9
            friendly_name: "Zone Vie"
            device_class: temperature
            value_template:  "{{state_attr('climate.domicile_zone_vie', 'current_temperature')}}"
```
It work, but binary_sensor.temp_zone_vie make me a state with "." and no ",".
So i think, some trouble bring me bug. 
Look history :
![image](https://user-images.githubusercontent.com/32144431/123619970-04660700-d80a-11eb-9cec-3d6ae17d4ef6.png)
isn't a graph like this:
![image](https://user-images.githubusercontent.com/32144431/123620072-21023f00-d80a-11eb-80ba-accbd6768a77.png)
And, i can't try to use the stat in node red or other..
I think it's because the value uploaded by airzone need a new format !?

**Comment by gabrio79** [comment]
I'm not sure that is a bug... but you could try to apply 

`{{ states('binary_sensor. temp_zone_vie').replace(',','\.') }}`

**Comment by landaisbenj** [comment]
I try but it's break the entity:

![image](https://user-images.githubusercontent.com/32144431/123645329-89f7b000-d826-11eb-9e44-32bf6cd1bede.png)


You talk about what settings ? Aircloud or Home assistant ? Because Home assistant look like be good..

**Comment by landaisbenj** [comment]
```
    temp_zone_vie:
      unique_id: 4cbf0f03-2f7e-4697-ad20-098a1288f4c9
      friendly_name: "Zone Vie"
      device_class: temperature
      value_template:  "{{state_attr('climate.domicile_zone_vie', 'current_temperature').replace(',','.')}}"
```

**Comment by gabrio79** [comment]
i think that replace doesn't works on state_attr, you need to creata another binary_sensor (ie: temp_zone_vie_wit_point)  
something like

```
temp_zone_vie_wit_point:
      unique_id: 4cbf0f03-2f7e-4697-ad20-098a12s88f4c9
      device_class: temperature
      value_template:  "{{ states('binary_sensor.temp_zone_vie_wit_point').replace(',','\.') }}"
```
